spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "22dbe7c6f0efc098e2f7fcd62476f4a2"
            redirect-uri: "http://localhost:8080/auth/login/kakao"
            scope: profile_nickname, account_email
            authorization-grant-type: authorization_code
        provider:
          kakao:
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  secret-key: "9393cd22aca2983b5a4af6e5c70b43fb92a359a8784282ffc29c2c57dde9c1ba4a8cc6aa11301c1b80313c12dd2a891674fcae44e07e81e7ff3b06144b7ccd79"
  expiration-time: 86400000

logging:
  level:
    org:
      springframework:
        security=DEBUG