kakao:
  registration:
    client-id: 6f47201bc042699a7bffec10c96e3327
    client-secret: xDLCTNAF1cVgSGgtTGTBa2Shq8LYHLAh
    redirect-uri: "http://localhost:5173/login/callback/kakao"
    scope: profile_nickname, account_email
    authorization-grant-type: authorization_code
    client-authentication-method: client_secret_post
  provider:
    authorization-uri: https://kauth.kakao.com/oauth/authorize
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    user-name-attribute: id

jwt:
  secret-key: "9393cd22aca2983b5a4af6e5c70b43fb92a359a8784282ffc29c2c57dde9c1ba4a8cc6aa11301c1b80313c12dd2a891674fcae44e07e81e7ff3b06144b7ccd79"
  access-token-expiration: 3600000    # Access Token 만료 시간 (1시간)
  refresh-token-expiration: 1209600000
